scrape_configs:
  - job_name: "otel-collector"
    scrape_interval: 30s
    static_configs:
      - targets: ["otel-collector:8889"]
    basic_auth:
      username: infisical
      password: infisical
