// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";



import { TImmutableDBKeys } from "./models";

export const UserSecretsSchema = z.object({
  id: z.string().uuid(),
  userId: z.string().uuid(),
  secretName: z.string(),
  orgId: z.string().uuid(),
  secretValue: z.string(),
  salt: z.string(),
  iv: z.string(),
  tag: z.string(),
  createdAt: z.date(),
  updatedAt: z.date(),
  secretType: z.string()
});

export type TUserSecrets = z.infer<typeof UserSecretsSchema>;
export type TUserSecretsInsert = Omit<z.input<typeof UserSecretsSchema>, TImmutableDBKeys>;
export type TUserSecretsUpdate = Partial<Omit<z.input<typeof UserSecretsSchema>, TImmutableDBKeys>>;
